apiVersion: apps/v1
kind: Deployment
metadata:
  name: fwddtuit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fwddtuit
  template:
    metadata:
      labels:
        app: fwddtuit
    spec:
      containers:
      - image: okteto.dev/dcufhn:latest
        name: fwddtuit
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "dc87c4e5-c206-40c9-bd68-633cbc7f784f"
        - name: Vless_Path
          value: "/fuuded"
        - name: Vmess_UUID
          value: "dc87c4e5-c206-40c9-bd68-633cbc7f784f"
        - name: Vmess_Path
          value: "/fuuded"
        - name: Share_Path
          value: "/v2link"
